AWSTemplateFormatVersion: 2010-09-09
Description: Browser Emulator

Parameters:
  ImageId:
    Type: AWS::EC2::Image::Id
    Description: A base Amazon EC2 image ID.
    Default: ami-0b6c6ebed2801a5cb
  GitRef:
    Type: String
    Description: Git tag or branch to checkout (e.g., 'v3.0.0', 'main', 'develop')
    Default: "v3.0.0"

Resources:
  BrowserInstance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT1H
        Count: 1
    Properties:
      ImageId: !Ref ImageId
      InstanceType: "t3.xlarge"
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName
    # Add KeyName: [your ssh key] to be able to access this instance
      BlockDeviceMappings:
      - DeviceName: "/dev/sda1"
        Ebs:
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: "50"
      UserData:
        "Fn::Base64":
          !Sub |
          #!/bin/bash
          git clone https://github.com/OpenVidu/openvidu-loadtest.git /opt/openvidu-loadtest
          cd /opt/openvidu-loadtest/browser-emulator
          git checkout ${GitRef}
          echo 'AWS_STACK=${AWS::StackId}' | sudo tee -a /etc/environment
          echo 'AWS_REGION=${AWS::Region}' | sudo tee -a /etc/environment
          chmod +x ./prepare_scripts/*.sh
          chmod +x ./*.sh
          ./prepare_scripts/install_base.sh > /var/log/install.log 2>&1
          usermod -aG docker ubuntu
          usermod -aG syslog ubuntu
          usermod -aG video ubuntu
          chown -R ubuntu:ubuntu /opt/openvidu-loadtest/
          echo "@reboot cd /opt/openvidu-loadtest/browser-emulator && CI=true pnpm install > /var/log/pnpm_install.log 2>&1 && pnpm run build > /var/log/build.log 2>&1 && pnpm run start:prod > /var/log/crontab.log 2>&1" 2>&1 | crontab -u ubuntu -
          apt-get install -y linux-aws-edge
          ./notify-aws.sh > /var/log/notify_aws.log 2>&1
