services:

  loadtest-controller:
    build:
      context: ../loadtest-controller
      dockerfile: Dockerfile
    image: loadtest-controller:local
    container_name: loadtest-controller-e2e
    restart: no
    environment:
      LOADTEST_CONFIG: ${LOADTEST_CONFIG:-/config/config.yaml}
      PLATFORM_URL: ${PLATFORM_URL:-https://localhost:7443}
      PLATFORM_APIKEY: ${PLATFORM_APIKEY:-devkey}
      PLATFORM_APISECRET: ${PLATFORM_APISECRET:-secret}
      RESULTS_DIR: /results
    networks:
      - browseremulator
    depends_on:
      browser-emulator:
        condition: service_healthy
    volumes:
      - ${LOCAL_CONFIG_DIR:-./config}:/config
      - ${LOCAL_RESULTS_DIR:-./results}:/results
      
  browser-emulator:
    build:
      context: ../browser-emulator
      dockerfile: Dockerfile
    image: browser-emulator:local
    container_name: browser-emulator-e2e
    restart: no
    environment:
        SERVER_PORT: ${SERVER_PORT:-5000}
        WEBSOCKET_PORT: ${WEBSOCKET_PORT:-5001}
        RUNNING_IN_DOCKER: true
        DOCKER_NETWORK_NAME: browseremulator-e2e
        DOCKER_BROWSER_EMULATOR_HOST: browser-emulator
        MEDIAFILES_HOST_DIR: ${MEDIAFILES_HOST_DIR}
        SCRIPTS_LOGS_HOST_DIR: ${SCRIPTS_LOGS_HOST_DIR}
        METRICBEAT_CONFIG: ${METRICBEAT_CONFIG}
    stop_grace_period: 60s
    networks:
      - browseremulator
    volumes:
      - ../browser-emulator/recordings/chrome:/app/recordings/chrome
      - ../browser-emulator/recordings/qoe:/app/recordings/qoe
      - ../browser-emulator/stats:/app/stats
      - ../browser-emulator/logs:/app/logs
      - ../browser-emulator/mediafiles:/app/mediafiles
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/openvidu-loadtest:/tmp/openvidu-loadtest

networks:
  browseremulator:
    name: browseremulator-e2e
