services:
    browser-emulator:
        build:
            context: .
            dockerfile: Dockerfile
        image: browser-emulator:local
        container_name: browser-emulator
        restart: unless-stopped
        environment:
            SERVER_PORT: ${SERVER_PORT:-5000}
            WEBSOCKET_PORT: ${WEBSOCKET_PORT:-5001}
            COM_MODULE: ${COM_MODULE:-livekit}
            RUNNING_IN_DOCKER: true
            DOCKER_NETWORK_NAME: browseremulator
            DOCKER_BROWSER_EMULATOR_HOST: browser-emulator
            MEDIAFILES_HOST_DIR: ${MEDIAFILES_HOST_DIR:-${PWD}/mediafiles}
            SCRIPTS_LOGS_HOST_DIR: ${SCRIPTS_LOGS_HOST_DIR:-${PWD}/logs}
            METRICBEAT_CONFIG: ${METRICBEAT_CONFIG:-${PWD}/browser-emulator/src/assets/metricbeat-config/metricbeat.yml}
            DISABLE_HTTPS: ${DISABLE_HTTPS:-false}
        stop_grace_period: 60s
        ports:
            - '${SERVER_PORT:-5000}:${SERVER_PORT:-5000}'
            - '${WEBSOCKET_PORT:-5001}:${WEBSOCKET_PORT:-5001}'
        networks:
            - browseremulator
        volumes:
            - ./recordings/chrome:/app/recordings/chrome
            - ./recordings/qoe:/app/recordings/qoe
            - ./stats:/app/stats
            - ./logs:/app/logs
            - ./mediafiles:/app/mediafiles
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    browseremulator:
        name: browseremulator
