# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  config.vm.box = "ubuntu/jammy64"

  config.vm.network "forwarded_port", guest: 5000, host: 5000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5001, host: 5001, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5900, host: 5900, host_ip: "127.0.0.1"

  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /opt/openvidu-loadtest/browser-emulator
    chown -R vagrant:vagrant /opt/openvidu-loadtest
  SHELL

  config.vm.synced_folder "./src", "/opt/openvidu-loadtest/browser-emulator/src"
  config.vm.synced_folder "./qoe_scripts", "/opt/openvidu-loadtest/browser-emulator/qoe_scripts"
  config.vm.synced_folder "./recording_scripts", "/opt/openvidu-loadtest/browser-emulator/recording_scripts"
  config.vm.synced_folder "./recordings", "/opt/openvidu-loadtest/browser-emulator/recordings"
  config.vm.provision "file", source: "./package.json", destination: "/opt/openvidu-loadtest/browser-emulator/package.json"
  config.vm.provision "file", source: "./prepare_no_qoe_firefox.sh", destination: "/opt/openvidu-loadtest/browser-emulator/prepare_no_qoe_firefox.sh"
  config.vm.provision "file", source: "./download_mediafiles.sh", destination: "/opt/openvidu-loadtest/browser-emulator/download_mediafiles.sh"
  config.vm.provision "file", source: "./tsconfig.json", destination: "/opt/openvidu-loadtest/browser-emulator/tsconfig.json"
  config.vm.provision "file", source: "./debug_vnc_local.sh", destination: "/opt/openvidu-loadtest/browser-emulator/debug_vnc.sh"

  config.vm.synced_folder "./public", "/opt/openvidu-loadtest/browser-emulator/public"
  config.vm.synced_folder "./public-lk", "/opt/openvidu-loadtest/browser-emulator/public-lk"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = "6"
  end

  config.vm.provision "shell", inline: <<-SHELL
    cd /opt/openvidu-loadtest/browser-emulator
    chmod +x ./*.sh
    ./prepare_no_qoe_firefox.sh
    usermod -aG docker vagrant
    usermod -aG syslog vagrant
    usermod -aG video vagrant
    chown -R vagrant:vagrant /opt/openvidu-loadtest
    crontab -r -u ubuntu
    echo '@reboot cd /opt/openvidu-loadtest/browser-emulator && npm run build && npm run start:prod-livekit-firefox > /var/log/crontab.log 2>&1' 2>&1 | crontab -u vagrant -
    curl -sSL https://get.livekit.io | bash
    (crontab -u vagrant -l ; echo '@reboot livekit-server --dev > /var/log/livekit.log 2>&1') | crontab -u vagrant -
    ./debug_vnc.sh
    reboot now
  SHELL
end
