name: Browser Emulator Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ vars.LABEL_WORKER_SELFHOSTED }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
  
      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Vagrant & VirtualBox
        run: |
          sudo bash actions-scripts/install-vagrant-virtualbox.sh

      - name: Resolve Vagrant parent box version and hash
        id: resolve_vagrant_box
        run: |
          bash actions-scripts/resolve-vagrant-box.sh

      - name: Install project dependencies
        run: |
          cd browser-emulator
          pnpm install

      - name: Run tests
        run: |
          cd browser-emulator
          pnpm run test:all
