name: Build and upload browser-emulator base box

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ vars.LABEL_WORKER_SELFHOSTED }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 10
  
      - name: Setup Node.js with pnpm
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'

      - name: Install Vagrant & VirtualBox
        run: |
          sudo bash actions-scripts/install-vagrant-virtualbox.sh

      - name: Fill .env file with secrets
        run: |
          cd browser-emulator
          cat > .env << EOF
          HCP_CLIENT_ID=${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET=${{ secrets.HCP_CLIENT_SECRET }}
          ORGANIZATION_ID=${{ secrets.ORGANIZATION_ID }}
          PROJECT_ID=${{ secrets.PROJECT_ID }}
          REGISTRY_NAME=${{ secrets.REGISTRY_NAME }}
          EOF

      - name: Create and upload Vagrant box
        run: |
          cd browser-emulator
          bash ./create_and_upload_vagrant_box.sh

