name: Build and upload browser-emulator base box

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ vars.LABEL_WORKER_SELFHOSTED }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: 10
  
      - name: Setup Node.js with pnpm
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24'

      - name: Install Vagrant & VirtualBox
        run: |
          sudo bash actions-scripts/install-vagrant-virtualbox.sh

      - name: Fill .env file with secrets
        run: |
          cd browser-emulator
          cat > .env << EOF
          HCP_CLIENT_ID=${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET=${{ secrets.HCP_CLIENT_SECRET }}
          ORGANIZATION_ID=${{ secrets.ORGANIZATION_ID }}
          PROJECT_ID=${{ secrets.PROJECT_ID }}
          REGISTRY_NAME=${{ secrets.REGISTRY_NAME }}
          EOF

      - name: Create and upload Vagrant box
        run: |
          cd browser-emulator
          bash ./create_and_upload_vagrant_box.sh

