name: Loadtest Controller Unit And Integration Tests

on:
  push:
    paths:
      - 'loadtest-controller/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
    get-docker-gid:
        runs-on: ${{ vars.LABEL_WORKER_SELFHOSTED }}
        outputs:
            gid: ${{ steps.gid.outputs.result }}
        steps:
            - name: Clean workspace from previous run
              run: sudo rm -rf "${{ github.workspace }}"/*
              shell: bash

            - name: Get Docker group GID
              id: gid
              run: echo "result=$(stat -c '%g' /var/run/docker.sock)" >> "$GITHUB_OUTPUT"

    unit-test:
        needs: get-docker-gid
        runs-on: ${{ vars.LABEL_WORKER_SELFHOSTED }}
        container:
            image: maven:3.9.14-eclipse-temurin-25
            options: --user 1000:1000 -v /var/run/docker.sock:/var/run/docker.sock --group-add ${{ needs.get-docker-gid.outputs.gid }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Build and unit tests
              run: |
                cd loadtest-controller
                mvn -Dtest=io.openvidu.loadtest.unit.**.*Test clean test

            - name: Run integration tests
              run: |
                cd loadtest-controller
                mvn -Dtest=io.openvidu.loadtest.integration.**.*Test test

    cleanup:
      needs: unit-test
      if: ${{ always() }}
      runs-on: ${{ vars.LABEL_WORKER_SELFHOSTED }}
      steps:
        - name: Clean up
          uses: OpenVidu/actions/cleanup@040cbfd01320475801d7b12e33769e0d55a737a8 # v1.0.21