name: Loadtest Controller Unit Test

on:
  workflow_dispatch:

jobs:
    unit-test:
        runs-on: ${{ vars.LABEL_WORKER_SELFHOSTED }}
        steps:
            - name: Setup JDK
              uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
              with:
                distribution: 'temurin'
                java-version: '21'

            - name: Checkout repository
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Build and test
              run: |
                cd loadtest-controller
                mvn clean test

            - name: Clean up
              if: always()
              uses: OpenVidu/actions/cleanup@35d136377813cf9b0b23d12d16d57864ccf3a8c2 # v1.0.2